# Name of target (without file extension, must be in SRC_DIR)
TARGET      = flashboot

# Project Sources (file names to use in SRC_DIR) and Global Library Sources (file names to use from LIB_DIR/src)
# WARNING: start.S must be first in the SRC_SOURCES list. This is to ensure it is placed in the appropriate memory location
SRC_SOURCES	= start.S main.c rv4th.c uart.c spi.c flash_memory.c
LIB_SOURCES	= 
EXTENSIONS	= i

# Chip Global Libraries and Linker Script
LIB_DIR		= ../lib
LD_DIR		= $(LIB_DIR)/linker
LD_SCRIPT	= $(LD_DIR)/MCU-bootrom.ld

# MCU Libraries
LIB_SRC_DIR = $(LIB_DIR)/src
LIB_INC_DIR = $(LIB_DIR)/include

# Project Files Source
SRC_DIR		= ./src
INC_DIR		= ./include
OBJ_DIR		= ./obj
BIN_DIR		= ./bin

# RAM and ROM Sizes
RAM_START	= `cat $(LD_DIR)/RAM_START.txt`
RAM_SIZE	= `cat $(LD_DIR)/RAM_SIZE.txt`
ROM_START	= `cat $(LD_DIR)/ROM_START.txt`
ROM_SIZE	= `cat $(LD_DIR)/ROM_SIZE.txt`

# Compiler flags
# Unused: Generate assembly listings for each C file: -Wa,-ahls=$*.lst
# Note: the -flto flag initiates link time optimization. It seems to force the compiler/linker to include only the functions explicitly used by the main function in the final output file. It also seems to require interrupts to have the __attribute__ prefix. This means that only the functions that are called by the main function and the interrupts will be added to the final binary file.
OPTIMIZATION_FLAGS = -Os -flto
#OPTIMIZATION_FLAGS = -flto
ARCH	= rv32$(EXTENSIONS)
CFLAGS	= -Werror -Wall -Wunused -march=$(ARCH) $(OPTIMIZATION_FLAGS) -D__nostdlib__ -I $(GCC_INC_DIR) -I $(INC_DIR) -I $(LIB_INC_DIR) -g
LFLAGS	= -lgcc -march=$(ARCH) $(OPTIMIZATION_FLAGS) -nostartfiles -Wl,-Bstatic,-T,$(LD_SCRIPT),-Map,$(BIN_DIR)/$(TARGET).map,--cref -L $(LD_DIR) -g

##################################################
### TOOLCHAIN DIRECTORIES
##################################################
# ifdef RISCV
# 	RISCV_DIR = ${RISCV}
# else
# 	RISCV_DIR = /opt/riscv
# endif

# For openSUSE VM on Poseidon
RISCV_DIR	= /opt/xpack-riscv-none-elf-gcc-14.2.0-2

RISCV_TOOLCHAIN_DIR	= $(RISCV_DIR)
PYTHON_DIR	= ../../python
GCC_INC_DIR	= $(RISCV_TOOLCHAIN_DIR)/riscv-none-elf/include
CC			= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-gcc
LD			= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-ld
AR			= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-ar
AS			= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-gcc
GASP		= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-gasp
NM			= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-nm
OBJCOPY		= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-objcopy
OBJDUMP		= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-objdump
RANLIB		= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-ranlib
STRIP		= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-strip
SIZE		= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-size
READELF		= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-readelf
GDB			= $(RISCV_TOOLCHAIN_DIR)/bin/riscv-none-elf-gdb
MAKETXT		= srec_cat
CP			= cp -p
RM			= rm -f
MV			= mv
MKDIR		= mkdir
RCF			= $(PYTHON_DIR)/ihex2rcf.py

# Dependencies
SRC_OBJECTS	= $(patsubst %,%.src.o,$(SRC_SOURCES))
LIB_OBJECTS	= $(patsubst %,%.lib.o,$(LIB_SOURCES))

SOURCES		= $(patsubst %,$(SRC_DIR)/%,$(SRC_SOURCES)) $(patsubst %,$(LIB_DIR)/%,$(LIB_SOURCES))
OBJECTS     = $(patsubst %,$(OBJ_DIR)/%,$(SRC_OBJECTS)) $(patsubst %,$(OBJ_DIR)/%,$(LIB_OBJECTS))

HEADERS     =  $(wildcard $(GCC_INC_DIR)/*.h) $(wildcard $(LIB_INC_DIR)/*.h) $(wildcard $(INC_DIR)/*.h)

##################################################
### COMPILATION RULES
##################################################

# Make the entire project
.PHONY: all
all: $(BIN_DIR)/$(TARGET).hex $(BIN_DIR)/$(TARGET).lst $(BIN_DIR)/$(TARGET).dump $(BIN_DIR)/rom.rcf

# Step 1: Src files to object files 
# Compile project source files from the project source directory into object files
$(OBJ_DIR)/%.src.o: $(SRC_DIR)/% $(HEADERS)
	@echo ""
	@echo "> Compiling project source file $<"
	@echo ""
	$(CC) -c $(CFLAGS) $< -o $@
	
# Step 1b: Lib files to object files
# Compile library source files from the library source directory into object files
$(OBJ_DIR)/%.lib.o: $(LIB_SRC_DIR)/% $(HEADERS)
	@echo ""
	@echo "> Compiling library source file $<"
	@echo ""
	$(CC) -c $(CFLAGS) $< -o $@

# Step 2: Object files to elf / binary files
# Link object files together to create binary elf output file, show memory usage
$(BIN_DIR)/$(TARGET).elf: $(OBJECTS)
	@echo ""
	@echo "> Linking $@"
	@echo ""
	$(CC) $(LFLAGS) $(OBJECTS) -o $@

# Step 3: elf to hex file
# Convert elf file into Intel hex file
$(BIN_DIR)/%.hex: $(BIN_DIR)/%.elf
	@echo ""
	@echo "> Creating output hex file $@"
	@echo ""
	$(OBJCOPY) -O ihex $< $@

# Step 4: elf to lst file (list of data)
# Create assembly lst file
$(BIN_DIR)/%.lst: $(BIN_DIR)/%.elf
	@echo ""
	@echo "> Creating C-to-assembly lst file $@"
	@echo ""
	$(OBJDUMP) --prefix-addresses --show-raw-insn -SrlD $< > $@
	@make memory -s

# Step 4b: Create HDL memory initialization file
# Create ROM RCF file
$(BIN_DIR)/rom.rcf: $(BIN_DIR)/$(TARGET).hex
	@echo ""
	@echo "> Creating boot ROM RCF file $@"
	@echo ""
	$(RCF) $< $@ $(ROM_START) $(ROM_SIZE) 32 --default 0x00000000

# Step 5: elf to dump file (for debugging purposes)
# Create disassembly dump file - Maxx Seminario 09/27/2025
# $(BIN_DIR)/$(TARGET).dump: $(BIN_DIR)/$(TARGET).elf
# 	@echo ""
# 	@echo "> Creating disassembly dump file $@"
# 	@echo ""
# 	$(OBJDUMP) -D -S --prefix-addresses --show-raw-insn $< > $@
# Create disassembly dump file (explicit rule)
$(BIN_DIR)/$(TARGET).dump: $(BIN_DIR)/$(TARGET).elf
	@echo ""
	@echo "> Creating disassembly dump file $@"
	@echo ""
	$(OBJDUMP) --disassemble-all --disassemble-zeroes \
		--section=.text --section=.text.startup --section=.text.init \
		--section=.data --section=.rodata --section=.bss \
		--prefix-addresses --show-raw-insn \
		$< > $@


# Added rule to dump just the 4th interpreter object file - Maxx Seminario 09/27/2025
# Run as: make bin/rv4th.dump
# Special compilation of rv4th.c without LTO for clean disassembly
$(OBJ_DIR)/rv4th_for_dump.o: $(SRC_DIR)/rv4th.c $(HEADERS)
	@echo ""
	@echo "> Compiling rv4th.c without LTO for disassembly"
	@echo ""
	$(CC) -c -march=$(ARCH) -Os -D__nostdlib__ \
		-I $(GCC_INC_DIR) -I $(INC_DIR) -I $(LIB_INC_DIR) \
		-g $(SRC_DIR)/rv4th.c -o $@

# Create clean rv4th dump with only executable code
$(BIN_DIR)/rv4th.dump: $(OBJ_DIR)/rv4th_for_dump.o
	@echo ""
	@echo "> Creating rv4th executable code dump"
	@echo ""
	$(OBJDUMP) --disassemble-all --prefix-addresses --show-raw-insn \
		--section=.text --section=.text.* \
		$(OBJ_DIR)/rv4th_for_dump.o > $@
	@echo "rv4th dump created with `grep -c '^[0-9a-f]* <' $@` functions"

	
##################################################
### HELPER RULES
##################################################

# Remove junk
.PHONY: tidy
tidy:
	@echo ""
	@echo "> Tidying up"
	@echo ""
	find $(OBJ_DIR) -type f -regextype posix-extended -iregex '.*\.(o)' -delete
	find $(BIN_DIR) -type f -regextype posix-extended -iregex '.*\.(map|xout|out|d|lst|map)' -delete

# Remove all non-source compilation artifacts
.PHONY: clean
clean: tidy
	@echo ""
	@echo "> Cleaning"
	@echo ""
	find $(BIN_DIR) -type f -regextype posix-extended -iregex '.*\.(hex|elf|rcf|hdlmem|dump)' -delete

# Print the memory usage of the target
.PHONY: memory
memory:
	@echo ""
	@echo "> Memory usage for $(TARGET)"
	@echo "    text is length of program in bytes (decimal)"
	@echo "    data is length of global vars in bytes (decimal)"
	@echo "    bss is length of uninitialized vars in bytes (decimal)"
	@echo "    dec is combined memory usage in bytes (decimal)"
	@echo ""
	$(SIZE) $(BIN_DIR)/$(TARGET).elf --format=berkeley --radix=10

# Set up the folder hierarchy
.PHONY: setup
setup:
	@if [ ! -d $(SRC_DIR) ] ; then $(MKDIR) $(SRC_DIR) ; fi
	@if [ ! -d $(INC_DIR) ] ; then $(MKDIR) $(INC_DIR) ; fi
	@if [ ! -d $(OBJ_DIR) ] ; then $(MKDIR) $(OBJ_DIR) ; fi
	@if [ ! -d $(BIN_DIR) ] ; then $(MKDIR) $(BIN_DIR) ; fi
	@echo "!.gitignore" > $(SRC_DIR)/.gitignore
	@echo "!.gitignore" > $(INC_DIR)/.gitignore
	@echo "*" > $(OBJ_DIR)/.gitignore && echo "!.gitignore" >> $(OBJ_DIR)/.gitignore
	@echo "!.gitignore" > $(BIN_DIR)/.gitignore
