tclmode

# Generated by Genus(TM) Synthesis Solution 19.15-s090_1, revision 1.479a
# Generated on: Sun Nov 09 14:29:56 CST 2025 (Sun Nov 09 20:29:56 UTC 2025)

set_screen_display -noprogress
set_dofile_abort exit

### Alias mapping flow is enabled. ###
# Root attribute 'wlec_rtl_name_mapping_flow' was 'false'.
# Root attribute 'alias_flow'                 was 'true'.

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         true

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required &&
    $wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set_log_file fv/MCU/rtl_to_fv_map.log -replace

usage -auto -elapse

set_verification_information rtl_fv_map_db

read_implementation_information fv/MCU -revised fv_map

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set env(RC_VERSION)     "19.15-s090_1"
set env(CDN_SYNTH_ROOT) "/opt/cadence/GENUS191/tools.lnx86"
set CDN_SYNTH_ROOT      "/opt/cadence/GENUS191/tools.lnx86"
set env(CW_DIR) "/opt/cadence/GENUS191/tools.lnx86/lib/chipware"
set CW_DIR      "/opt/cadence/GENUS191/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_notranslate_modules -library -both sram1p16k_hvt_pg rom_hvt_pg

add_search_path ../ip/rom_hvt_pg ../ip/sram1p16k_hvt_pg in/ /opt/design_kits/TSMC65-IP/arm/sc10/hvt/aci/sc-ad10/ecsm-timing/ -library -both
read_library -liberty -both /home/mseminario2/chips/myshkin/genus/../ip/rom_hvt_pg/rom_hvt_pg_nldm_tt_1p00v_1p00v_25c_syn.lib /home/mseminario2/chips/myshkin/genus/../ip/sram1p16k_hvt_pg/sram1p16k_hvt_pg_nldm_tt_1p00v_1p00v_25c_syn.lib /opt/design_kits/TSMC65-IP/arm/sc10/hvt/aci/sc-ad10/ecsm-timing/scadv10_cln65gp_hvt_tt_1p0v_25c.lib

set_undriven_signal 0 -golden
set lec_version_required "16.20100"
if {$lec_version >= $lec_version_required} {
    set_naming_style genus -golden
} else {
    set_naming_style rc -golden
}
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden
set lec_version_required "17.10200"
if {$lec_version >= $lec_version_required} {
    set_naming_rule -ungroup_separator {_} -golden
}

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue.
# This option is only available with LEC 17.20-d301 or later.
set lec_version_required "17.20301"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -const_port_extend
}

# Align LEC's elaboration of VHDL configurations with Genus's.
# Genus message VHDL-674 may indicate the presence of this issue.
# This option is only available with LEC 18.10-p100 or later.
set lec_version_required "18.10"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -vhdl_elab_unspecified_config off
}
delete_search_path -all -design -golden
add_search_path ../hdl -design -golden
read_design -rangeconstraint -configuration  -enumconstraint -golden -lastmod -noelab  -vhdl 93  ../hdl/MCU/commune/fixed_float_types_c.vhdl -vhdl 93  ../hdl/MCU/commune/fixed_pkg_c.vhdl -vhdl 93  ../hdl/MCU/commune/FPMac.vhd -vhdl 93  ../hdl/MCU/commune/FPSigmoid.vhd -vhdl 93  ../hdl/MCU/constants.vhd -vhdl 93  ../hdl/MCU/MemoryMap.vhd -vhdl 93  ../hdl/MCU/commune/TieLow.vhd -vhdl 93  ../hdl/MCU/commune/ClkGate_cmn65gp_ARM.vhd -vhdl 93  ../hdl/MCU/commune/ClockMuxGlitchFree_cmn65gp_ARM.vhd -vhdl 93  ../hdl/MCU/commune/CRC16.vhd -vhdl 93  ../hdl/MCU/commune/ClkDivPower2.vhd -vhdl 93  ../hdl/MCU/periph/GPIO.vhd -vhdl 93  ../hdl/MCU/periph/SPI.vhd -vhdl 93  ../hdl/MCU/periph/UART.vhd -vhdl 93  ../hdl/MCU/periph/I2C.vhd -vhdl 93  ../hdl/MCU/periph/TIMER.vhd -vhdl 93  ../hdl/MCU/periph/SYSTEM.vhd -vhdl 93  ../hdl/MCU/periph/NPU.vhd -vhdl 93  ../hdl/MCU/periph/SARADC.vhd -vhdl 93  ../hdl/MCU/periph/AFE_FSM.vhd -vhdl 93  ../hdl/MCU/periph/AFE.vhd -vhdl 93  ../hdl/MCU/vesta/div.vhd -vhdl 93  ../hdl/MCU/vesta/alu.vhd -vhdl 93  ../hdl/MCU/vesta/extend.vhd -vhdl 93  ../hdl/MCU/vesta/regfile_sbirq.vhd -vhdl 93  ../hdl/MCU/vesta/irq_handler.vhd -vhdl 93  ../hdl/MCU/vesta/loadext.vhd -vhdl 93  ../hdl/MCU/vesta/store_ext.vhd -vhdl 93  ../hdl/MCU/vesta/branch_valid.vhd -vhdl 93  ../hdl/MCU/vesta/csr_unit.vhd -vhdl 93  ../hdl/MCU/vesta/datapath.vhd -vhdl 93  ../hdl/MCU/vesta/maindec.vhd -vhdl 93  ../hdl/MCU/vesta/controller.vhd -vhdl 93  ../hdl/MCU/vesta/c_dec.vhd -vhdl 93  ../hdl/MCU/vesta/vesta.vhd -vhdl 93  ../hdl/MCU/adddec.vhd -vhdl 93  ../hdl/MCU/MCU.vhd
elaborate_design -golden -root {MCU} -rootonly 

read_design -verilog95   -revised -lastmod -noelab fv/MCU/fv_map.v.gz
elaborate_design -revised -root {MCU}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge
set_flatten_model -gated_clock

set_flatten_model -balanced_modeling

#add_name_alias fv/MCU/fv_map.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff dlat -both

# modules were tagged with 'unresolved' attribute during synthesis
#   can cause non-equivalences if ports in Golden and Revised do not match
# attribute write_vlog_empty_module_for_black_box is set to false in synthesis
#   can cause non-equivalences since port directions will be inferred
add_black_box OscillatorCurrentStarved GlitchFilter PowerOnResetCheng -golden

# Reports the quality of the implementation information.
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
    check_verification_information
}

set_analyze_option -auto -report_map

write_hier_compare_dofile hier_tmp1.lec.do -verbose -noexact_pin_match -constraint -usage \
-replace -balanced_extraction -input_output_pin_equivalence \
-prepend_string "report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath $DATAPATH_SOLVER_OPTION -verbose"
run_hier_compare hier_tmp1.lec.do -dynamic_hierarchy

report_hier_compare_result -dynamicflattened

report_verification -hier -verbose

write_verification_information
report_verification_information

# Reports how effective the implementation information was.
# This command is only available with LEC 18.20-d330 or later.
set lec_version_required "18.20330"
if {$lec_version >= $lec_version_required} {
    report_implementation_information
}

set_system_mode lec

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
# This command is available with LEC 19.10-p100 or later.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required} {
analyze_results -logfiles fv/MCU/rtl_to_fv_map.log
}

vpxmode

exit -f
