set_clock_latency -source -early -min -rise  -0.41942 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -fall  -0.388561 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -rise  -0.41942 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -fall  -0.388561 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -rise  -0.41942 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -fall  -0.388561 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -rise  -0.41942 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -fall  -0.388561 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -rise  -0.589379 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -fall  -0.552665 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -rise  -0.589379 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -fall  -0.552665 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -rise  -0.589379 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -fall  -0.552665 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -rise  -0.589379 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -fall  -0.552665 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -rise  -0.280154 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -fall  -0.250076 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -rise  -0.280154 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -fall  -0.250076 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -rise  -0.280154 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -fall  -0.250076 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -rise  -0.280154 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -fall  -0.250076 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -rise  -0.590007 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -fall  -0.554012 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -rise  -0.590007 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -fall  -0.554012 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -rise  -0.590007 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -fall  -0.554012 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -rise  -0.590007 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -fall  -0.554012 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -rise  -0.259078 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -min -fall  -0.229029 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -rise  -0.259078 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -fall  -0.229029 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -rise  -0.259078 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -fall  -0.229029 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -rise  -0.259078 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -fall  -0.229029 [get_pins {spi1/sck_in}] -clock clk_sck1 
